### PR TITLE
Test: add richtext fuzz

### PR DESCRIPTION
**Pull request by Leeeon233**

### CODE REVIEW

**Comment by zxch3n** [comment]
What's the difference with the existing one?

**Comment by Leeeon233** [comment]
> What's the difference with the existing one?

checkout consistency and event correctness.

**Comment by Leeeon233** [comment]
Are there other actions that need to be tested?  @zxch3n

**Comment by zxch3n** [comment]
Time machine should be covered. There should be an `Action` variance that checkouts to an arbitrary valid version.

**Comment by Leeeon233** [comment]
> Time machine should be covered. There should be an `Action` variance that checkouts to an arbitrary valid version.

Is `check_history` not enough to cover the time machine?

**Comment by zxch3n** [comment]
No. There is no edit after time travel, which cannot find bugs like this #211 .

There are many corner cases that only arise when you combine `checkouts and edits.

**Pull request merged**
